#!/usr/bin/env bash
# installs nginx and configures it
apt-get update
apt-get -y install nginx
echo "server {
        listen 80;
        listen [::]:80;

        root /var/www/html/;
        server_name localhost;
}" > /etc/nginx/sites-available/default
echo "Hello World!" > /var/www/html/index.html
service nginx restart