#!/usr/bin/env bash
# installs nginx and configures it
apt-get update
apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html
echo "server {
        listen 80;
        listen [::]:80;

        server_name _;
        location / {
                root /var/www/html/;
                index index.html index.htm;
        }
}" > /etc/nginx/sites-available/default
nginx -t
service nginx restart