#!/usr/bin/env bash
# configures nginx server

echo "server {
        listen 80;
        listen [::]:80;

        root /var/www/html/;
        location /redirect_me {
        return 301 "var/www/html/redirect_me.html";
    }
}" > /etc/nginx/sites-available/default

service nginx restart