#!/usr/bin/env bash
#configures redirect me

redirect="        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}"
sed -i "s/'}'/$redirect/" /etc/nginx/sites-available/default