#!/usr/bin/env bash
# configures nginx server

echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
        listen 80;
        listen [::]:80;

        root /var/www/html/;
        server_name localhost;

        location /redirect_me {
        return 301 var/www/html/redirect_me.html;
    }

    error_page 404 /404.html;

        location /404.html {
            root /var/www/html/;
            internal;
        }
}" > /etc/nginx/sites-available/default

service nginx restart