#!/usr/bin/env bash
# configures nginx server
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
hostname=$(hostname)
echo "server {
        listen 80;
        listen [::]:80;

        root /var/www/html/;
        index index.html;
        server_name _;

        location /redirect_me {
        return 301 var/www/html/redirect_me.html;
    }

    error_page 404 /404.html;

        location /404.html {
            root /var/www/html/;
            internal;
        }

    location / {
        add_header X-served-by $hostname;
    }
}" > /etc/nginx/sites-available/default

service nginx restart