#!/usr/bin/env bash
#creates a pid file
echo $$ > /var/run/myscript.pid
while true
do
	trap 'echo "I hate the kill command"' SIGTERM
	trap 'rm /var/run/myscript.pid' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/myscript.pid' SIGQUIT
	echo "To infinity and beyond"
done
