#!/usr/bin/env bash
# prints all 12 hours of the day
hour=0
while [ $hour -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -lt 60 ]
	do
		echo "$minute"
		((minute++))
	done
	((hour++))
done
